name: Style Dictionary
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "tokens/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      # Convert tokens according to Style Dictionary config
      - run: npm run build
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Tokens
